alias art="php artisan"
alias pls="php please"
alias cu="composer update"
alias cgu="composer global update"
alias rm="trash"
alias rf="trash -rf"
alias bubu="brew update && brew upgrade && brew cleanup && brew doctor"
alias tower="gittower"
alias npu="npm update"
alias ngu="npm -g update"
alias touchdb="touch database/database.sqlite"
alias plsuser="cp ~/.dotfiles/statamic/user@example.com.yaml users/user@example.com.yaml && echo '\''User created.'\'"
alias artuser="art tinker --execute="App\Models\User::create(['name' => 'Example User', 'email' => 'user@example.com', 'password' => bcrypt('password')]);"
alias plsenv="cp ~/.dotfiles/statamic/.env.example ./.env.example && echo '\''.env created.'\'"